### ISSUE TITLE
Fix badges in readme

### ISSUE THREAD

**Issue by 7rulnik** [7rulnik/postcss-flexibility#111]

**Comment by ChineseEngineer** [comment]
Ie9 not supported?

**Comment by 7rulnik** [comment]
@ChineseEngineer I don't know :D It's just postcss plugin. For browser support you should create issue in [flexibility](https://github.com/jonathantneal/flexibility) project.

But seems that you need this:

> To start using Flexbox in Internet Explorer 8 & 9 or any older browser, download the flexibility.js script and include it anywhere on your page.

Check the readme of flexibility ;)

**Comment by 7rulnik** [comment]
Fixed in #126
