### ISSUE TITLE
The ability to exclude blocks of code from being processed

### ISSUE THREAD

**Issue by Designer023** [7rulnik/postcss-flexibility#29]
Hi,

I'm running into issues with the site i'm working with. Long story short, flexibility is awesome, but there is one block of selectors I'd like to exclude from being processed because they are that complicated the plugin can't handle it :) This is a long shot at a feature request.

e.g.

    // #flexibility-stop
    .block of selectors {... }
    // #flexibility-start

**Comment by 7rulnik** [comment]
Hi @Designer023 

I agree that execlude selectors from processing really good idea, but not sure that comment block is best way to do it. I thought about `display: flex no-process` or something like this, but I don't really like it because it's not «real» css.

**Comment by Designer023** [comment]
Hi! @7rulnik,

Yeah i'm not keen on adding comments either, but using non-real css seems worse. The way i was thinking is similar to what the [scss-lint project does](https://github.com/brigade/scss-lint/#disabling-linters-via-source). It's not ideal, but it's the best I can come up with other than having a config file with a white / black list of selectors. Disabling it where needed inline seems to make more sense to me :)

**Comment by 7rulnik** [comment]
@Designer023 
I just release **v1.1.0**. Now you can [exclude](https://github.com/7rulnik/postcss-flexibility#excluding-rules) rules. For now you can exclude rule by adding comment. In next releases I will try to implement excluding for code blocks.

**Comment by Designer023** [comment]
@7rulnik Thank you. You are amazing :)
